// <auto-generated />
using System;
using FromTheFuture.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FromTheFuture.Infrastructure.Migrations
{
    [DbContext(typeof(FutureDbContext))]
    partial class FutureDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FromTheFuture.Domain.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users","user");
                });

            modelBuilder.Entity("FromTheFuture.Domain.Users.User", b =>
                {
                    b.OwnsMany("FromTheFuture.Domain.Users.FutureBoxes.FutureBox", "_futureBoxes", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Name")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<Guid>("UserId")
                                .HasColumnType("uniqueidentifier");

                            b1.HasKey("Id");

                            b1.HasIndex("UserId");

                            b1.ToTable("FutureBoxes","user");

                            b1.WithOwner()
                                .HasForeignKey("UserId");

                            b1.OwnsMany("FromTheFuture.Domain.Users.FutureBoxes.FutureBoxItem", "_futureBoxItems", b2 =>
                                {
                                    b2.Property<Guid>("FutureItemId")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<Guid>("FutureBoxId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.HasKey("FutureItemId", "FutureBoxId");

                                    b2.HasIndex("FutureBoxId");

                                    b2.ToTable("FutureBoxItems","user");

                                    b2.WithOwner()
                                        .HasForeignKey("FutureBoxId");
                                });
                        });

                    b.OwnsMany("FromTheFuture.Domain.Users.FutureItems.FutureItem", "_futureItems", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Name")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<int>("Type")
                                .HasColumnType("int");

                            b1.Property<Guid>("UserId")
                                .HasColumnType("uniqueidentifier");

                            b1.HasKey("Id");

                            b1.HasIndex("UserId");

                            b1.ToTable("FutureItems","user");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
